# Colores
BLANCO = (255, 255, 255)
NEGRO = (0, 0, 0)
GRIS = (206, 206, 206)
AZUL = (30, 136, 229)

#Seteos Juego
ANCHO_PANTALLA = 400
ALTO_PANTALLA = 450
ALTO_TEXTO = 50
CANTIDAD_TARJETAS_H = 4
CANTIDAD_TARJETAS_V = 4
ANCHO_TARJETA = ANCHO_PANTALLA / CANTIDAD_TARJETAS_H
ALTO_TARJETA = (ALTO_PANTALLA - ALTO_TEXTO)/ CANTIDAD_TARJETAS_V
PATH_RECURSOS = r"C:\Users\alumno\Desktop\clase_16\recursos"
